version: '3.8'

volumes:
  prometheus_data: {}

networks:
  monitoring:
    driver: bridge

services:

  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 6655
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
